name: Merge Pull Requests into 'main'

on:
  push:
    branches: [main]
    paths-ignore:
      - '.editorconfig'
      - 'ReadMe.md'
      - 'ChangeLog.md'
      - '.github/workflows/PullRequest.yml'
      - '.github/workflows/Release.yml'

permissions:
  packages: write

env:
  DOTNET_NOLOGO: true

jobs:
  build_and_test:
    name: Build and Test (RELEASE)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Build version prefix/suffix
        run: |
          echo "VERSION_PREFIX=$(( ${{ github.run_number }} )).0.0" >> $GITHUB_ENV
          echo "VERSION_SUFFIX=beta" >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true -p:VersionPrefix=$VERSION_PREFIX --version-suffix $VERSION_SUFFIX

      - run: dotnet test --configuration Release --no-build
            
  build_and_test_with_code_coverage:
    name: Build and Test with CodeCov (DEBUG)
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Debug

      - run: dotnet test --configuration Debug --verbosity minimal --no-build --collect:"XPlat Code Coverage" --results-directory "./.codecoverage"

      - name: Code coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: "./.codecoverage"
          fail_ci_if_error: true
