name: Publish Console Apps

on:
  push:
    tags:
      - "*.*.*"
    paths-ignore:
      - '.editorconfig'
      - 'ReadMe.md'
      - 'ChangeLog.md'
      - '.github/workflows/PullRequest.yml'
      - '.github/workflows/MergeToMain.yml'

permissions:
  contents: write
  packages: write

env:
  DOTNET_NOLOGO: true

jobs:
  build_and_create_a_console_apps:
    name: Build, Create a Console App
    runs-on: ubuntu-latest
    strategy:
      matrix:
        runtime: [win-x64, linux-x64, osx-x64]

    steps:

      - name: Calculate version from the Commit Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v5

      - run: dotnet restore --verbosity minimal

      - run: dotnet build --configuration Release -p:ContinuousIntegrationBuild=true -p:version=${{ env.RELEASE_VERSION }}

      - name: Publish for ${{ matrix.runtime }}
        run: |
            dotnet publish ./code/SimpleRemoteGitRepoBackup.Console/WorldDomination.SimpleRemoteGitRepoBackup.Console.csproj --configuration Release --output ./artifacts/${{ matrix.runtime }} -r ${{ matrix.runtime }}
            ls -al ./artifacts/${{ matrix.runtime }}/
            if [ "${{ matrix.runtime }}" == "win-x64" ]; then
              mv ./artifacts/${{ matrix.runtime }}/SimpleRemoteGitRepoBackup.exe ./publish/SimpleRemoteGitRepoBackup-${{ matrix.runtime }}.exe
            else
              mv ./artifacts/${{ matrix.runtime }}/SimpleRemoteGitRepoBackup ./publish/SimpleRemoteGitRepoBackup-${{ matrix.runtime }}
            fi

      - name: Publish artifacts
        uses: actions/upload-artifact@v5
        with:
          name: SimpleRemoteGitBackup.${{ env.RELEASE_VERSION }}.${{ matrix.runtime }}
          path: ./artifacts/${{ matrix.runtime }}/

      - name: Upload release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          name: SimpleRemoteGitBackup.${{ env.RELEASE_VERSION }}.{{ matrix.runtime }}
          files: ./artifacts/${{ matrix.runtime }}/*
          body_path: ${{ github.workspace }}-ChangeLog.md
